/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* ReadCSV(char* csvFile);
extern char* ReadJSON(char* jsonStr);
extern char* ReadNDJSON(char* jsonStr);
extern char* GetAPIJSON(char* endpoint, char* headers, char* queryParams);

// Print displays the DataFrame in a simple tabular format.
//
extern char* Show(char* dfJson, int chars, int record_count);
extern char* Head(char* dfJson, int chars);
extern char* Tail(char* dfJson, int chars);
extern char* Vertical(char* dfJson, int chars, int record_count);

// ColumnOp applies an operation (identified by opName) to the columns
// specified in colsJson (a JSON array of strings) and stores the result in newCol.
// The supported opName cases here are "SHA256" and "SHA512". You can add more operations as needed.
//
extern char* ColumnOp(char* dfJson, char* newCol, char* opName, char* colsJson);

// ColumnCollectList applies CollectList on the specified source column
// and creates a new column.
//
extern char* ColumnCollectList(char* dfJson, char* newCol, char* source);

// ColumnCollectSet applies CollectSet on the specified source column
// and creates a new column.
//
extern char* ColumnCollectSet(char* dfJson, char* newCol, char* source);

// ColumnSplit applies Split on the specified source column with the given delimiter
// and creates a new column.
//
extern char* ColumnSplit(char* dfJson, char* newCol, char* source, char* delim);
extern char* DFColumns(char* dfJson);

// DFCount returns the number of rows in the DataFrame.
//
extern int DFCount(char* dfJson);

// DFCountDuplicates returns the count of duplicate rows.
// It accepts a JSON array of column names (or an empty array to use all columns).
//
extern int DFCountDuplicates(char* dfJson, char* colsJson);

// DFCountDistinct returns the count of unique rows (or unique values in the provided columns).
// Accepts a JSON array of column names (or an empty array to use all columns).
//
extern int DFCountDistinct(char* dfJson, char* colsJson);

// DFCollect returns the collected values from a specified column as a JSON-array.
//
extern char* DFCollect(char* dfJson, char* colName);

#ifdef __cplusplus
}
#endif
